name: Auto-Test

on:
  push:
    paths:
      - 'app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - run: gradle wrapper --gradle-version latest
      - run: gradle build -Prelease
      - uses: actions/upload-artifact@v7
        with:
          name: APK
          path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk