name: Auto-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: '18'
      - name: Set up Gradle CLI
        uses: gradle/actions/setup-gradle@v6.0.1
        with:
          gradle-version: wrapper
      - name: Build
        run: gradle build
      - name: Upload Build
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp [Github Actions]"
          git add .
          if git commit -m "build by Github Actions"; then
              git push
          fi
#      - name: Upload APK artifact
        # uses: actions/upload-artifact@v7
        # with:
        #   name: APK
        #   path: app/build/outputs/apk/release/app-release.apk
